name: codex_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  connectivity_plus:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:

  # State Management & Utilities
  provider:
  shared_preferences:
  image_picker:
  appwrite:
  mime:
  intl:
  cupertino_icons:
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - images/

dependency_overrides:
  flutter_web_auth_2: ^4.1.0

